[project]
name = "project-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "psutil>=7.0.0",
    "uvicorn>=0.35.0",
    "websockets>=15.0.1",
]
