
name: build the docker image and push to Docker Hub
on: push

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: read the repository contents
      uses: actions/checkout@v4
    
    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: build the docker image and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: chank616/project-demo:latest

    - name: deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: "${{ secrets.SSH_HOST }}"
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          echo "start deploy..."
          sudo docker pull chank616/project-demo:latest
          sudo docker stop project-demo || true
          sudo docker rm project-demo || true
          sudo docker run -d --name project-demo -p 8000:8000 docker.1ms.run/chank616/project-demo:latest
          echo "deploy over!"