
name: build the docker image and push to Docker Hub
on: push

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: read the repository contents
      uses: actions/checkout@v4
    
    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: build the docker image and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: chank616/project-demo:latest